package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ajouter_etudController {
    @FXML
    private Button buttonadd;
    @FXML
    private TextField F_name;
    @FXML
    private TextField L_name;
    @FXML
    private TextField email;
    @FXML
    private TextField password;
    @FXML
    private TextField filiere;
    @FXML 
    private Label erorrinput;
    private boolean areFieldsEmpty() {
	    return    email.getText().isEmpty()
	            | password.getText().isEmpty()
	            |F_name.getText().isEmpty()
	            | L_name.getText().isEmpty()
	            |filiere.getText().isEmpty();
	}
    
    @FXML
    public void ajouterEtu(ActionEvent event) {
        // TODO Autogenerated
        String emailc = email.getText();
        String passwordc = password.getText();
        String Fname = F_name.getText();
        String Lname = L_name.getText();
        String Filiere = filiere.getText();
        String sql = "INSERT INTO etudiant (Nom, Prenom, Email, password, Filiere) VALUES (?, ?, ?, ?, ?)";
        String url = "jdbc:mysql://localhost:3306/gestinpfe";
        String username = "root";
        String pass = "";
        try {
            Connection con = DriverManager.getConnection(url, username, pass);
            PreparedStatement preparedStatement = con.prepareStatement(sql);

          if(areFieldsEmpty()) {erorrinput.setText("error : input vide");}
          else {
            preparedStatement.setString(1, Fname);
            preparedStatement.setString(2, Lname);
            preparedStatement.setString(3, emailc);
            preparedStatement.setString(4, passwordc);
            preparedStatement.setString(5, Filiere);

            
            int rowsAffected = preparedStatement.executeUpdate();

           
            preparedStatement.close();
            con.close();

            
            if (rowsAffected > 0) {
                System.out.println("Student added successfully!");
            } else {
                System.out.println("Failed to add student. No rows affected.");
            }
          }
        } catch (SQLException e) {
           
            e.printStackTrace();
            System.out.println("Error adding student: " + e.getMessage());
        }
    }
}
